# Generated by Django 4.0.4 on 2022-06-28 19:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 28, 12, 17, 43, 998441)),
        ),
    ]
